export const KEYS_PRESENT_IN_PDF: string[] = [
  // ! Table of Contents
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_YOUR_TITLE_AND_YOUR_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP1_TITLE_AND_EMP1_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP2_TITLE_AND_EMP2_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP3_TITLE_AND_EMP3_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP4_TITLE_AND_EMP4_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP5_TITLE_AND_EMP5_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP6_TITLE_AND_EMP6_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP7_TITLE_AND_EMP7_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP8_TITLE_AND_EMP8_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP9_TITLE_AND_EMP9_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP10_TITLE_AND_EMP10_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD1_TITLE_AND_BRD1_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD2_TITLE_AND_BRD2_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD3_TITLE_AND_BRD3_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER1_TITLE_AND_PARTNER1_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER2_TITLE_AND_PARTNER2_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER3_TITLE_AND_PARTNER3_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER4_TITLE_AND_PARTNER4_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER5_TITLE_AND_PARTNER5_NAME",

  // ! Cover Page - Step 2
  "YOUR_COMPANY_NAME",
  "YOUR_PRODUCT_OR_SERVICE_DESCRIPTION",
  "YOUR_COVER_PAGE_DATE",
  "YOUR_FIRST_NAME_AND_LAST_NAME",
  "YOUR_EMAIL_ADDRESS",
  "YOUR_PHONE_NUMBER",
  "YOUR_INTERNET_ADDRESS",
  "YOUR_POST_ADDRESS",
  "YOUR_COVER_PAGE_LEGAL_DISCLOSURE",

  // ! Executive Summary - Step 3

  // ? Company and Market Overview
  "FINAL_BP_EXECUTIVE_SUMMARY_COMPANY_AND_MARKET_OVERVIEW",

  // ? Target Customer
  "FINAL_BP_EXECUTIVE_SUMMARY_TARGET_CUSTOMER",

  // ? Management Team
  "FINAL_BP_EXECUTIVE_SUMMARY_MANAGEMENT_TEAM",

  // ? Board/Advisors (Optional)
  "FINAL_BP_EXECUTIVE_SUMMARY_BOARD_ADVISORS",

  // ? Market Problem & Solution
  "FINAL_BP_EXECUTIVE_SUMMARY_MARKET_PROBLEM_AND_SOLUTION",

  // ? Significant Recent Company Milestone (Optional)
  "FINAL_BP_EXECUTIVE_SUMMARY_SIGNIFICANT_RECENT_COMPANY_MILESTONE",

  // ? Product Image (Optional)
  "FINAL_BP_EXECUTIVE_SUMMARY_PRODUCT_IMAGE",

  // ? Footnote (Optional)
  "FINAL_BP_EXECUTIVE_SUMMARY_COMPANY_AND_MARKET_OVERVIEW_DATA_SOURCE_FOOTNOTE",

  // ! Management Team Overview - Step 4

  // ? Management Team
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_YOUR_TITLE_AND_YOUR_NAME",
  "FINAL_BP_PIC_YOU",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_YOUR_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP1_TITLE_AND_EMP1_NAME",
  "FINAL_BP_PIC_EMP1",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP1_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP2_TITLE_AND_EMP2_NAME",
  "FINAL_BP_PIC_EMP2",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP2_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP3_TITLE_AND_EMP3_NAME",
  "FINAL_BP_PIC_EMP3",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP3_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP4_TITLE_AND_EMP4_NAME",
  "FINAL_BP_PIC_EMP4",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP4_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP5_TITLE_AND_EMP5_NAME",
  "FINAL_BP_PIC_EMP5",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP5_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP6_TITLE_AND_EMP6_NAME",
  "FINAL_BP_PIC_EMP6",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP6_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP7_TITLE_AND_EMP7_NAME",
  "FINAL_BP_PIC_EMP7",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP7_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP8_TITLE_AND_EMP8_NAME",
  "FINAL_BP_PIC_EMP8",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP8_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP9_TITLE_AND_EMP9_NAME",
  "FINAL_BP_PIC_EMP9",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP9_BIO",

  // ? Optional
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP10_TITLE_AND_EMP10_NAME",
  "FINAL_BP_PIC_EMP10",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMP10_BIO",

  // ? Board / Advisors (Optional)
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD1_TITLE_AND_BRD1_NAME",
  "FINAL_BP_PIC_BRD1",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD1_BIO",

  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD2_TITLE_AND_BRD2_NAME",
  "FINAL_BP_PIC_BRD2",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD2_BIO",

  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD3_TITLE_AND_BRD3_NAME",
  "FINAL_BP_PIC_BRD3",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_BRD3_BIO",

  // ? Outsourced Partners (Optional)
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER1_TITLE_AND_PARTNER1_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER1_BIO",

  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER2_TITLE_AND_PARTNER2_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER2_BIO",

  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER3_TITLE_AND_PARTNER3_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER3_BIO",

  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER4_TITLE_AND_PARTNER4_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER4_BIO",

  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER5_TITLE_AND_PARTNER5_NAME",
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_PARTNER5_BIO",

  // ? Employee Recruiting Strategy
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMPLOYEE_RECRUITING_STRATEGY",

  // ? Employee Incentivizing, Motivation and Retention Strategy
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_EMPLOYEE_INCENTIVIZING_MOTIVATION_AND_RETENTION_STRATEGY",

  // ? Additional Resources to Hire
  "FINAL_BP_MANAGEMENT_TEAM_OVERVIEW_ADDITIONAL_RESOURCES_TO_HIRE",

  // ! Product / Services - Step 5

  // ? Product/Service Overview
  "FINAL_BP_PRODUCT_OR_SERVICE_OVERVIEW",

  // ? Quality Control (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_QUALITY_CONTROL",

  // ? Packaging (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_PACKAGING",

  // ? Production (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_PRODUCTION",

  // ? Current Price Strategy
  "FINAL_BP_PRODUCT_OR_SERVICE_CURRENT_PRICE_STRATEGY",

  // ? Future Price Strategy (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_FUTURE_PRICE_STRATEGY",

  // ? Bundle Price Strategy (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_BUNDLE_PRICE_STRATEGY",

  // ? Volume Discounts (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_VOLUME_DISCOUNTS",

  // ? Financing (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_FINANCING",

  // ? Freemium or Premium Pricing Strategy (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_FREEMIUM_OR_PREMIUM_PRICING_STRATEGY",

  // ? Input Prices (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_INPUT_PRICES",

  // ? Distribution Strategy
  "FINAL_BP_PRODUCT_OR_SERVICE_DISTRIBUTION_STRATEGY",

  // ? Return Policy (Optional)
  "FINAL_BP_PRODUCT_OR_SERVICE_RETURN_POLICY",

  // ! Customer and Market Commentary - Step 6

  // ? Who is the Customer?
  "FINAL_BP_CUSTOMER_AND_MARKET_WHO_IS_THE_CUSTOMER",

  // ? Customer Concentration
  "FINAL_BP_CUSTOMER_AND_MARKET_CUSTOMER_CONCENTRATION",

  // ? Customer Attainment Strategy
  "FINAL_BP_CUSTOMER_AND_MARKET_CUSTOMER_ATTAINMENT_STRATEGY",

  // ? Customer Survey Research (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_CUSTOMER_SURVEY_RESEARCH",

  // ? Customer Service
  "FINAL_BP_CUSTOMER_AND_MARKET_CUSTOMER_SERVICE",

  // ? Customer Response Time (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_CUSTOMER_RESPONSE_TIME",

  // ? Customer Loyalty Program (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_CUSTOMER_LOYALTY_PROGRAM",

  // ? Customer Profile Documentation (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_CUSTOMER_PROFILE_DOCUMENTATION",

  // ? General Industry Trends / Drivers
  "FINAL_BP_CUSTOMER_AND_MARKET_GENERAL_INDUSTRY_TRENDS_DRIVERS",

  // ? Industry Risks
  "FINAL_BP_CUSTOMER_AND_MARKET_INDUSTRY_RISKS",

  // ? Warranty Policy (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_WARRANTY_POLICY",

  // ? Industry Search Trends (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_INDUSTRY_SEARCH_TRENDS",

  // ? Barriers to Entry
  "FINAL_BP_CUSTOMER_AND_MARKET_BARRIERS_TO_ENTRY",

  // ? Total Addressable Market (T.A.M.)
  "FINAL_BP_CUSTOMER_AND_MARKET_TOTAL_ADDRESSABLE_MARKET",

  // ? Percent of the T.A.M. We Plan on Capturing in 5 Years (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_PERCENT_TAM_WE_PLAN_ON_CAPTURING_IN_5_YEARS",

  // ? Seasonality (Optional)
  "FINAL_BP_CUSTOMER_AND_MARKET_SEASONALITY",

  // ! Competition - Step 7

  // ? Largest Competitor Description
  "FINAL_BP_COMPETITION_LARGEST_COMPETITOR_DESCRIPTION",

  // ? Strengths of Largest Competitor
  "FINAL_BP_COMPETITION_STRENGTHS_OF_LARGEST_COMPETITOR",

  // ? Weaknesses of Largest Competitor
  "FINAL_BP_COMPETITION_WEAKNESSES_OF_LARGEST_COMPETITOR",

  // ? 2nd Largest Competitor Description
  "FINAL_BP_COMPETITION_2ND_LARGEST_COMPETITOR_DESCRIPTION",

  // ? Strengths of 2nd Largest Competitor
  "FINAL_BP_COMPETITION_STRENGTHS_OF_2ND_LARGEST_COMPETITOR",

  // ? Weaknesses of 2nd Largest Competitor
  "FINAL_BP_COMPETITION_WEAKNESSES_OF_2ND_LARGEST_COMPETITOR",

  // ? 3rd Largest Competitor Description
  "FINAL_BP_COMPETITION_3RD_LARGEST_COMPETITOR_DESCRIPTION",

  // ? Strengths of 3rd Largest Competitor
  "FINAL_BP_COMPETITION_STRENGTHS_OF_3RD_LARGEST_COMPETITOR",

  // ? Weaknesses of 3rd Largest Competitor
  "FINAL_BP_COMPETITION_WEAKNESSES_OF_3RD_LARGEST_COMPETITOR",

  // ? 4th Largest Competitor Description (Optional)
  "FINAL_BP_COMPETITION_4TH_LARGEST_COMPETITOR_DESCRIPTION",

  // ? Strengths of 4th Largest Competitor (Optional)
  "FINAL_BP_COMPETITION_STRENGTHS_OF_4TH_LARGEST_COMPETITOR",

  // ? Weaknesses of 4th Largest Competitor (Optional)
  "FINAL_BP_COMPETITION_WEAKNESSES_OF_4TH_LARGEST_COMPETITOR",

  // ? 5th Largest Competitor Description (Optional)
  "FINAL_BP_COMPETITION_5TH_LARGEST_COMPETITOR_DESCRIPTION",

  // ? Strengths of 5th Largest Competitor (Optional)
  "FINAL_BP_COMPETITION_STRENGTHS_OF_5TH_LARGEST_COMPETITOR",

  // ? Weaknesses of 5th Largest Competitor (Optional)
  "FINAL_BP_COMPETITION_WEAKNESSES_OF_5TH_LARGEST_COMPETITOR",

  // ? Discussion of Our Strengths Compared to the Competition's Strengths
  "FINAL_BP_COMPETITION_DISCUSSION_OF_OUR_STRENGTHS_COMPARED_TO_THE_COMPETITIONS_STRENGTHS",

  // ? Discussion of Our Weaknesses Compared to the Competition's Weaknesses
  "FINAL_BP_COMPETITION_DISCUSSION_OF_OUR_WEAKNESSES_COMPARED_TO_THE_COMPETITIONS_WEAKNESSES",

  // ? Discussion of Our Management Compared to the Competition's Management
  "FINAL_BP_COMPETITION_DISCUSSION_OF_OUR_MANAGEMENT_COMPARED_TO_THE_COMPETITIONS_MANAGEMENT",

  // ? Discussion of Our Price Strategy Compared to the Competition's Price Strategy
  "FINAL_BP_COMPETITION_DISCUSSION_OF_OUR_PRICE_STRATEGY_COMPARED_TO_THE_COMPETITIONS_PRICE_STRATEGY",

  // ! Go-to Market Strategy - Step 8

  // ? Online Distribution Strategy
  "FINAL_BP_GO_TO_MARKET_STRATEGY_ONLINE_DISTRIBUTION_STRATEGY",

  // ? Offline Distribution Strategy
  "FINAL_BP_GO_TO_MARKET_STRATEGY_OFFLINE_DISTRIBUTION_STRATEGY",

  // ? Direct Distribution Strategy
  "FINAL_BP_GO_TO_MARKET_STRATEGY_DIRECT_DISTRIBUTION_STRATEGY",

  // ? Indirect Distribution Strategy
  "FINAL_BP_GO_TO_MARKET_STRATEGY_INDIRECT_DISTRIBUTION_STRATEGY",

  // ? Cost of Distribution
  "FINAL_BP_GO_TO_MARKET_STRATEGY_COST_OF_DISTRIBUTION",

  // ! Sales and Marketing Strategy - Step 9

  // ? Sales Force Structure (Optional)
  "FINAL_BP_SALES_AND_MARKETING_STRATEGY_SALES_FORCE_STRUCTURE",

  // ? Sales Force Incentives (Optional)
  "FINAL_BP_SALES_AND_MARKETING_STRATEGY_SALES_FORCE_INCENTIVES",

  // ? Sales Force Registration / License Certification (Optional)
  "FINAL_BP_SALES_AND_MARKETING_STRATEGY_SALES_FORCE_REGISTRATION_OR_LICENSE_CERTIFICATION",

  // ? Online Marketing (Social Media) Strategy
  "FINAL_BP_SALES_AND_MARKETING_STRATEGY_ONLINE_MARKETING_SOCIAL_MEDIA_STRATEGY",

  // ? Lead Generation Strategy
  "FINAL_BP_SALES_AND_MARKETING_STRATEGY_LEAD_GENERATION_STRATEGY",

  // ? Offline Media Strategy
  "FINAL_BP_SALES_AND_MARKETING_STRATEGY_OFFLINE_MEDIA_STRATEGY",

  // ! Milestone - Step 10

  // ? Future Products or Services Milestones
  "FINAL_BP_MILESTONES_FUTURE_PRODUCTS_OR_SERVICES_MILESTONES",

  // ? Future Revenue Milestones
  "FINAL_BP_MILESTONES_FUTURE_REVENUE_MILESTONES",

  // ? Future Break-Even Milestone
  "FINAL_BP_MILESTONES_FUTURE_BREAK_EVEN_MILESTONE",

  // ? Units Sales Milestones (Optional)
  "FINAL_BP_MILESTONES_UNITS_SALES_MILESTONES",

  // ? TAM Milestones (Optional)
  "FINAL_BP_MILESTONES_TAM_MILESTONES",

  // ? Profit Margins Milestones (Optional)
  "FINAL_BP_MILESTONES_PROFIT_MARGINS_MILESTONES",

  // ? Geographic Milestones (Optional)
  "FINAL_BP_MILESTONES_GEOGRAPHIC_MILESTONES",

  // ? Other Future Milestones (Optional)
  "FINAL_BP_MILESTONES_OTHER_FUTURE_MILESTONES",

  // ? Future Exit Strategy Milestones (Optional)
  "FINAL_BP_MILESTONES_FUTURE_EXIT_STRATEGY_MILESTONES",

  // ? Revenue Milestones Achieved (Optional)
  "FINAL_BP_MILESTONES_REVENUE_MILESTONES_ACHIEVED",

  // ? Units Sales Milestones Achieved (Optional)
  "FINAL_BP_MILESTONES_UNITS_SALES_MILESTONES_ACHIEVED",

  // ? TAM Milestones Achieved (Optional)
  "FINAL_BP_MILESTONES_TAM_MILESTONES_ACHIEVED",

  // ? Break Even Milestone Achieved (Optional)
  "FINAL_BP_MILESTONES_BREAK_EVEN_MILESTONE_ACHIEVED",

  // ? Profit Margins Milestones Achieved (Optional)
  "FINAL_BP_MILESTONES_PROFIT_MARGINS_MILESTONES_ACHIEVED",

  // ? Products or Services Milestones Achieved (Optional)
  "FINAL_BP_MILESTONES_PRODUCTS_OR_SERVICES_MILESTONES_ACHIEVED",

  // ? Geographic Milestones Achieved (Optional)
  "FINAL_BP_MILESTONES_GEOGRAPHIC_MILESTONES_ACHIEVED",

  // ? Other Milestones Achieved (Optional)
  "FINAL_BP_MILESTONES_OTHER_MILESTONES_ACHIEVED",

  // ! Other / Miscellaneous (i.e., Risks) - Step 11

  // ? Future Technology Development Risks that Can Impact Our Business Model
  "FINAL_BP_OTHER_MISCELLANEOUS_FUTURE_TECHNOLOGY_DEVELOPMENT_RISKS_THAT_CAN_IMPACT_OUR_BUSINESS_MODEL",

  // ? Future Competition Risks
  "FINAL_BP_OTHER_MISCELLANEOUS_FUTURE_COMPETITION_RISKS",

  // ? Macroeconomic Developments Risks
  "FINAL_BP_OTHER_MISCELLANEOUS_MACROECONOMIC_DEVELOPMENTS_RISKS",

  // ? Disaster Recovery Strategy
  "FINAL_BP_OTHER_MISCELLANEOUS_DISASTER_RECOVERY_STRATEGY",

  // ? Other Potential Risks
  "FINAL_BP_OTHER_MISCELLANEOUS_OTHER_POTENTIAL_RISKS",

  // ? What is the Most Misunderstood Aspect of Our Business Model?
  "FINAL_BP_OTHER_MISCELLANEOUS_WHAT_IS_THE_MOST_MISUNDERSTOOD_ASPECT_OF_OUR_BUSINESS_MODEL",

  // ! Financials

  // ? Revenue and Net Income Forecast Highlights
  "FINAL_BP_FINANCIALS_REVENUE_AND_NET_INCOME_FORECAST_HIGHLIGHTS",

  // ? Financial Ratios
  "FINAL_BP_FINANCIALS_RATIOS_1",
  "FINAL_BP_FINANCIALS_RATIOS_2",

  // ? Monthly Revenue Forecast
  "FINAL_BP_FINANCIALS_MONTHLY_REVENUE_FORECAST",

  // ? Quarterly Revenue Forecast
  "FINAL_BP_FINANCIALS_QUARTERLY_REVENUE_FORECAST",

  // ? Annual Revenue Forecast
  "FINAL_BP_FINANCIALS_ANNUAL_REVENUE_FORECAST",

  // ? Monthly Operating Income Expenses Forecast
  "FINAL_BP_FINANCIALS_MONTHLY_OPERATING_INCOME_EXPENSE_FORECAST",

  // ? Annual Operating Income Expenses Forecast
  "FINAL_BP_FINANCIALS_ANNUAL_OPERATING_INCOME_EXPENSE_FORECAST",

  // ? Quarterly Income Statement
  "FINAL_BP_FINANCIALS_QUARTERLY_INCOME_STATEMENT_FORECAST",

  // ? Annual Income Statement
  "FINAL_BP_FINANCIALS_ANNUAL_INCOME_STATEMENT_FORECAST",

  // ? Quarterly Balance Sheet
  "FINAL_BP_FINANCIALS_QUARTERLY_BALANCE_SHEET_FORECAST",

  // ? Annual Balance Sheet
  "FINAL_BP_FINANCIALS_ANNUAL_BALANCE_SHEET_FORECAST",

  // ? Quarterly Cash Flow Statement
  "FINAL_BP_FINANCIALS_QUARTERLY_CASH_FLOW_STATEMENT_FORECAST",

  // ? Annual Cash Flow Statement
  "FINAL_BP_FINANCIALS_ANNUAL_CASH_FLOW_STATEMENT_FORECAST",
];
